name: promptly
description: A collection of customizable interactive command-line components.
version: 1.0.0
repository: https://github.com/zoocityboy/promptly
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  args: ^2.3.0
  dart_console: ^4.1.0
  get_it: ^8.0.3
  meta: ^1.15.0
  tint: ^2.0.0
  version: ^3.0.2


dev_dependencies:
  lint: ^2.0.1
  test: ^1.25.14
  test_coverage_badge: ^0.3.2
