name: promptly_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  promptly:
    path: ../..

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
executables: 
  promptly_cli:
