name: promptly_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dart_console: ^4.1.1
  get_it: ^8.0.3
  meta: ^1.16.0

dev_dependencies:
  
  lints: ^5.0.0

  test: ^1.24.0
