name: Quality Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Test
        run: dart test
      - name: Test coverage
        run: dart test --coverage=coverage -r github
      - name: Generate coverage badge
        run: dart run test_coverage_badge
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/lcov.info