name: Quality Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Promptly cli
        working-directory: example/promptly_cli
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Test
        run: dart test
      - name: Test coverage
        run: dart test --coverage=coverage -r github
      - name: Generate coverage badge
        run: dart run test_coverage_badge
      - name: Commit coverage badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage_badge.svg
          git commit -m 'Add coverage badge'
          git push origin HEAD:${{ github.head_ref }}